---
apiVersion: triggers.tekton.dev/v1beta1
kind: Trigger
metadata:
  name: hello-world-trigger
spec:
  serviceAccountName: pipeline
  bindings:
    - ref: hello-world-app
  template:
    ref: hello-world-app